
/* Drop Tables 

DROP TABLE AUTHORITIES CASCADE CONSTRAINTS;
DROP TABLE CART CASCADE CONSTRAINTS;
DROP TABLE COMMENT_TBL CASCADE CONSTRAINTS;
DROP TABLE FOLLOW CASCADE CONSTRAINTS;
DROP TABLE HASHTAG CASCADE CONSTRAINTS;
DROP TABLE LIKES CASCADE CONSTRAINTS;
DROP TABLE MAP CASCADE CONSTRAINTS;
DROP TABLE MESSAGECONTENT CASCADE CONSTRAINTS;
DROP TABLE MESSAGE CASCADE CONSTRAINTS;
DROP TABLE PHOTOMUSEUM CASCADE CONSTRAINTS;
DROP TABLE MUSEUM CASCADE CONSTRAINTS;
DROP TABLE NOTICE CASCADE CONSTRAINTS;
DROP TABLE PDORDER CASCADE CONSTRAINTS;
DROP TABLE PAYMENT CASCADE CONSTRAINTS;
DROP TABLE PRODUCT CASCADE CONSTRAINTS;
DROP TABLE PHOTO CASCADE CONSTRAINTS;
DROP TABLE TEXT CASCADE CONSTRAINTS;
DROP TABLE POST CASCADE CONSTRAINTS;
DROP TABLE QNA CASCADE CONSTRAINTS;
DROP TABLE USERS CASCADE CONSTRAINTS;
*/

/* 필요 시퀀스 !!! */
-- USER
CREATE SEQUENCE SEQ_USER
NOCACHE
NOCYCLE;

-- POST
CREATE SEQUENCE SEQ_POST
NOCACHE
NOCYCLE;

-- COMMENT
CREATE SEQUENCE SEQ_COMMENT_TBL
NOCACHE
NOCYCLE;

-- PHOTO
CREATE SEQUENCE SEQ_PHOTO
NOCACHE
NOCYCLE;

-- PRODUCT
CREATE SEQUENCE SEQ_PRODUCT
NOCACHE
NOCYCLE;

-- MUSEUM
CREATE SEQUENCE SEQ_MUSEUM
NOCACHE
NOCYCLE;

-- MARKER
CREATE SEQUENCE SEQ_MARKER
NOCACHE
NOCYCLE;

-- TEXT
CREATE SEQUENCE SEQ_TEXT
NOCACHE
NOCYCLE;

-- ORDER
CREATE SEQUENCE SEQ_PAYMENT
NOCACHE
NOCYCLE;

-- MESSAGE
CREATE SEQUENCE SEQ_MESSAGE
NOCACHE
NOCYCLE;

-- QNA
CREATE SEQUENCE SEQ_QNA
NOCACHE
NOCYCLE;

-- NOTICE
CREATE SEQUENCE SEQ_NOTICE
NOCACHE
NOCYCLE;


/*시퀀스 삭제용 */
/*
DROP SEQUENCE SEQ_USER;
DROP SEQUENCE SEQ_POST;
DROP SEQUENCE SEQ_COMMENT_TBL;
DROP SEQUENCE SEQ_PHOTO;
DROP SEQUENCE SEQ_PRODUCT;
DROP SEQUENCE SEQ_MUSEUM;
DROP SEQUENCE SEQ_MARKER;
DROP SEQUENCE SEQ_TEXT;
DROP SEQUENCE SEQ_PAYMENT;
DROP SEQUENCE SEQ_MESSAGE;
DROP SEQUENCE SEQ_QNA;
DROP SEQUENCE SEQ_NOTICE;
*/




/* Create Tables */

CREATE TABLE AUTHORITIES
(
	-- USER_SEQ
	userNo number NOT NULL,
	-- 1- 회원
	authorities number
);


CREATE TABLE CART
(
	-- USER_SEQ
	userNo number NOT NULL,
	-- 생성순 PRODUCT_SEQ
	pdNo number NOT NULL
);


CREATE TABLE COMMENT_TBL
(
	-- COMMENT_SEQ
	cNo number NOT NULL,
	-- POST_SEQ
	postNo number NOT NULL,
	-- USER_SEQ
	userNo number NOT NULL,
	-- 1 원댓글
	cLevel number,
	cDate date DEFAULT SYSDATE,
	-- COMMENT_SEQ
	parentCNo number NOT NULL,
	PRIMARY KEY (cNo)
);


CREATE TABLE FOLLOW
(
	-- USER_SEQ
	userNo number NOT NULL,
	-- USER_SEQ
	followTargetId number NOT NULL
);


CREATE TABLE HASHTAG
(
	-- POST_SEQ
	postNo number NOT NULL,
	hashtag nvarchar2(10) NOT NULL
);


CREATE TABLE LIKES
(
	-- USER_SEQ
	userNo number NOT NULL,
	-- POST_SEQ
	postNo number NOT NULL
);


CREATE TABLE MAP
(
	-- POST_SEQ
	postNo number NOT NULL,
	-- 생성순서에 따라 MARKER_SEQ
	markerNo number NOT NULL,
	markerName nvarchar2(30),
	markerLocation nvarchar2(100),
	PRIMARY KEY (markerNo)
);


CREATE TABLE MESSAGE
(
	-- MESSAGE_SEQ
	msgNo number NOT NULL,
	-- USER_SEQ
	sUserNo number NOT NULL,
	-- USER_SEQ
	rUserNo number NOT NULL,
	-- 1- 보낼때
	-- 2- 받을때
	msgCode number,
	msgSend date DEFAULT SYSDATE,
	msgRead date DEFAULT SYSDATE,
	PRIMARY KEY (msgNo)
);


CREATE TABLE MESSAGECONTENT
(
	-- MESSAGE_SEQ
	msgNo number NOT NULL,
	msgContent nvarchar2(2000)
);


CREATE TABLE MUSEUM
(
	-- 생성순서대로 MUSEUM_SEQ
	mNo number NOT NULL,
	museumTitle nvarchar2(20),
	museumDescription nvarchar2(100),
	PRIMARY KEY (mNo)
);


CREATE TABLE NOTICE
(
	-- NOTICE_SEQ
	noticeNo number NOT NULL,
	-- USER_SEQ
	userNo number NOT NULL,
	-- 굳이
	noticeCode number,
	noticeTitle nvarchar2(30),
	noticeContent nvarchar2(2000),
	noticeDate date DEFAULT SYSDATE,
	-- 필요없을듯
	noticeCategory number,
	PRIMARY KEY (noticeNo)
);


CREATE TABLE PAYMENT
(
	-- ORDER_SEQ
	paymentNo number NOT NULL,
	-- USER_SEQ
	userNo number NOT NULL,
	paymentDate date DEFAULT SYSDATE,
	-- 원단위
	paymentTotal number,
	PRIMARY KEY (paymentNo)
);


CREATE TABLE PDORDER
(
	-- ORDER_SEQ
	paymentNo number NOT NULL,
	-- 생성순 PRODUCT_SEQ
	pdNo number NOT NULL
);


CREATE TABLE PHOTO
(
	-- PHOTO_SEQ
	photoNo number NOT NULL,
	-- POST_SEQ
	postNo number NOT NULL,
	photoWidth number NOT NULL,
	photoHeight number NOT NULL,
	photoSize number,
	photoName nvarchar2(200),
	photoUrl nvarchar2(200),
	PRIMARY KEY (photoNo)
);


CREATE TABLE PHOTOMUSEUM
(
	-- 생성순서대로 MUSEUM_SEQ
	mNo number NOT NULL,
	-- PHOTO_SEQ
	photoNo number NOT NULL
);


CREATE TABLE POST
(
	-- POST_SEQ
	postNo number NOT NULL,
	-- USER_SEQ
	userNo number NOT NULL,
	postTitle nvarchar2(25) NOT NULL,
	postHits number DEFAULT 0,
	-- 1 판매 2 낫판매
	postSellorNot number NOT NULL,
	-- 어차피 한정되어있는데 숫자로할지 멀로할지
	postCategory number,
	-- 코멘트허용여부
	-- 1- 허용
	-- 2- 비허용
	-- 판매글일시 무조건 1해야함
	-- 제약조건?< ? 
	postCorNot number DEFAULT 1 NOT NULL,
	-- 1- 전체공개
	-- 2- 팔로워한정
	postRead number DEFAULT 1,
	-- 좋아요개수 저장용
	postLikes number DEFAULT 0,
	postDate date DEFAULT SYSDATE,
	PRIMARY KEY (postNo)
);


CREATE TABLE PRODUCT
(
	-- 생성순 PRODUCT_SEQ
	pdNo number NOT NULL,
	-- PHOTO_SEQ
	photoNo number NOT NULL,
	-- 원단위숫자만
	pdPrice number NOT NULL,
	pdSalesNo number DEFAULT 0,
	pdDate date DEFAULT SYSDATE,
	PRIMARY KEY (pdNo)
);


CREATE TABLE QNA
(
	-- QNA_SEQ
	qnaNo number NOT NULL,
	-- USER_SEQ
	userNo number NOT NULL,
	-- 질문-1
	-- 답변-2
	qnaCode number,
	qnaTitle nvarchar2(30),
	qnaContent nvarchar2(2000),
	qnaDate date DEFAULT SYSDATE,
	-- 정해져있으니까 숫자코드로 구분할쥐
	qnaCategory number,
	PRIMARY KEY (qnaNo)
);


CREATE TABLE TEXT
(
	-- 시퀀스설정하지말고 순서따라서 1 2 3 입력 이거 되나?
	textNo number NOT NULL,
	-- POST_SEQ
	postNo number NOT NULL,
	textContent nvarchar2(2000),
	PRIMARY KEY (textNo)
);


CREATE TABLE USERS
(
	-- USER_SEQ
	userNo number NOT NULL,
	-- 20자, 영어소문자,숫자만 사용가능
	userId nvarchar2(20) NOT NULL UNIQUE,
	-- 영어대소문자특문 포함
	userPassword nvarchar2(30) NOT NULL,
	userEmail nvarchar2(40) NOT NULL UNIQUE,
	userName nvarchar2(10) NOT NULL,
	userNickname nvarchar2(20),
	userFing number DEFAULT 0,
	userFwer number DEFAULT 0,
	-- 기본값에 기본 프사 지정
	userProfile nvarchar2(300),
	PRIMARY KEY (userNo)
);



/* Create Foreign Keys */

ALTER TABLE COMMENT_TBL
	ADD FOREIGN KEY (parentCNo)
	REFERENCES COMMENT_TBL (cNo)
;


ALTER TABLE MESSAGECONTENT
	ADD FOREIGN KEY (msgNo)
	REFERENCES MESSAGE (msgNo)
;


ALTER TABLE PHOTOMUSEUM
	ADD FOREIGN KEY (mNo)
	REFERENCES MUSEUM (mNo)
;


ALTER TABLE PDORDER
	ADD FOREIGN KEY (paymentNo)
	REFERENCES PAYMENT (paymentNo)
;


ALTER TABLE PHOTOMUSEUM
	ADD FOREIGN KEY (photoNo)
	REFERENCES PHOTO (photoNo)
;


ALTER TABLE PRODUCT
	ADD FOREIGN KEY (photoNo)
	REFERENCES PHOTO (photoNo)
;


ALTER TABLE COMMENT_TBL
	ADD FOREIGN KEY (postNo)
	REFERENCES POST (postNo)
;


ALTER TABLE HASHTAG
	ADD FOREIGN KEY (postNo)
	REFERENCES POST (postNo)
;


ALTER TABLE LIKES
	ADD FOREIGN KEY (postNo)
	REFERENCES POST (postNo)
;


ALTER TABLE MAP
	ADD FOREIGN KEY (postNo)
	REFERENCES POST (postNo)
;


ALTER TABLE PHOTO
	ADD FOREIGN KEY (postNo)
	REFERENCES POST (postNo)
;


ALTER TABLE TEXT
	ADD FOREIGN KEY (postNo)
	REFERENCES POST (postNo)
;


ALTER TABLE CART
	ADD FOREIGN KEY (pdNo)
	REFERENCES PRODUCT (pdNo)
;


ALTER TABLE PDORDER
	ADD FOREIGN KEY (pdNo)
	REFERENCES PRODUCT (pdNo)
;


ALTER TABLE AUTHORITIES
	ADD FOREIGN KEY (userNo)
	REFERENCES USERS (userNo)
;


ALTER TABLE CART
	ADD FOREIGN KEY (userNo)
	REFERENCES USERS (userNo)
;


ALTER TABLE COMMENT_TBL
	ADD FOREIGN KEY (userNo)
	REFERENCES USERS (userNo)
;


ALTER TABLE FOLLOW
	ADD FOREIGN KEY (userNo)
	REFERENCES USERS (userNo)
;


ALTER TABLE FOLLOW
	ADD FOREIGN KEY (followTargetId)
	REFERENCES USERS (userNo)
;


ALTER TABLE LIKES
	ADD FOREIGN KEY (userNo)
	REFERENCES USERS (userNo)
;


ALTER TABLE MESSAGE
	ADD FOREIGN KEY (rUserNo)
	REFERENCES USERS (userNo)
;


ALTER TABLE MESSAGE
	ADD FOREIGN KEY (sUserNo)
	REFERENCES USERS (userNo)
;


ALTER TABLE NOTICE
	ADD FOREIGN KEY (userNo)
	REFERENCES USERS (userNo)
;


ALTER TABLE PAYMENT
	ADD FOREIGN KEY (userNo)
	REFERENCES USERS (userNo)
;


ALTER TABLE POST
	ADD FOREIGN KEY (userNo)
	REFERENCES USERS (userNo)
;


ALTER TABLE QNA
	ADD FOREIGN KEY (userNo)
	REFERENCES USERS (userNo)
;



/* Comments */

COMMENT ON COLUMN AUTHORITIES.userNo IS 'USER_SEQ';
COMMENT ON COLUMN AUTHORITIES.authorities IS '1- 회원';
COMMENT ON COLUMN CART.userNo IS 'USER_SEQ';
COMMENT ON COLUMN CART.pdNo IS '생성순 PRODUCT_SEQ';
COMMENT ON COLUMN COMMENT_TBL.cNo IS 'COMMENT_SEQ';
COMMENT ON COLUMN COMMENT_TBL.postNo IS 'POST_SEQ';
COMMENT ON COLUMN COMMENT_TBL.userNo IS 'USER_SEQ';
COMMENT ON COLUMN COMMENT_TBL.cLevel IS '1 원댓글';
COMMENT ON COLUMN COMMENT_TBL.parentCNo IS 'COMMENT_SEQ';
COMMENT ON COLUMN FOLLOW.userNo IS 'USER_SEQ';
COMMENT ON COLUMN FOLLOW.followTargetId IS 'USER_SEQ';
COMMENT ON COLUMN HASHTAG.postNo IS 'POST_SEQ';
COMMENT ON COLUMN LIKES.userNo IS 'USER_SEQ';
COMMENT ON COLUMN LIKES.postNo IS 'POST_SEQ';
COMMENT ON COLUMN MAP.postNo IS 'POST_SEQ';
COMMENT ON COLUMN MAP.markerNo IS '생성순서에 따라 MARKER_SEQ';
COMMENT ON COLUMN MESSAGE.msgNo IS 'MESSAGE_SEQ';
COMMENT ON COLUMN MESSAGE.sUserNo IS 'USER_SEQ';
COMMENT ON COLUMN MESSAGE.rUserNo IS 'USER_SEQ';
COMMENT ON COLUMN MESSAGE.msgCode IS '1- 보낼때
2- 받을때';
COMMENT ON COLUMN MESSAGECONTENT.msgNo IS 'MESSAGE_SEQ';
COMMENT ON COLUMN MUSEUM.mNo IS '생성순서대로 MUSEUM_SEQ';
COMMENT ON COLUMN NOTICE.noticeNo IS 'NOTICE_SEQ';
COMMENT ON COLUMN NOTICE.userNo IS 'USER_SEQ';
COMMENT ON COLUMN NOTICE.noticeCode IS '굳이';
COMMENT ON COLUMN NOTICE.noticeCategory IS '필요없을듯';
COMMENT ON COLUMN PAYMENT.paymentNo IS 'ORDER_SEQ';
COMMENT ON COLUMN PAYMENT.userNo IS 'USER_SEQ';
COMMENT ON COLUMN PAYMENT.paymentTotal IS '원단위';
COMMENT ON COLUMN PDORDER.paymentNo IS 'ORDER_SEQ';
COMMENT ON COLUMN PDORDER.pdNo IS '생성순 PRODUCT_SEQ';
COMMENT ON COLUMN PHOTO.photoNo IS 'PHOTO_SEQ';
COMMENT ON COLUMN PHOTO.postNo IS 'POST_SEQ';
COMMENT ON COLUMN PHOTOMUSEUM.mNo IS '생성순서대로 MUSEUM_SEQ';
COMMENT ON COLUMN PHOTOMUSEUM.photoNo IS 'PHOTO_SEQ';
COMMENT ON COLUMN POST.postNo IS 'POST_SEQ';
COMMENT ON COLUMN POST.userNo IS 'USER_SEQ';
COMMENT ON COLUMN POST.postSellorNot IS '1 판매 2 낫판매';
COMMENT ON COLUMN POST.postCategory IS '어차피 한정되어있는데 숫자로할지 멀로할지';
COMMENT ON COLUMN POST.postCorNot IS '코멘트허용여부
1- 허용
2- 비허용
판매글일시 무조건 1해야함
제약조건?< ? ';
COMMENT ON COLUMN POST.postRead IS '1- 전체공개
2- 팔로워한정';
COMMENT ON COLUMN POST.postLikes IS '좋아요개수 저장용';
COMMENT ON COLUMN PRODUCT.pdNo IS '생성순 PRODUCT_SEQ';
COMMENT ON COLUMN PRODUCT.photoNo IS 'PHOTO_SEQ';
COMMENT ON COLUMN PRODUCT.pdPrice IS '원단위숫자만';
COMMENT ON COLUMN QNA.qnaNo IS 'QNA_SEQ';
COMMENT ON COLUMN QNA.userNo IS 'USER_SEQ';
COMMENT ON COLUMN QNA.qnaCode IS '질문-1
답변-2';
COMMENT ON COLUMN QNA.qnaCategory IS '정해져있으니까 숫자코드로 구분할쥐';
COMMENT ON COLUMN TEXT.textNo IS '시퀀스설정하지말고 순서따라서 1 2 3 입력 이거 되나?';
COMMENT ON COLUMN TEXT.postNo IS 'POST_SEQ';
COMMENT ON COLUMN USERS.userNo IS 'USER_SEQ';
COMMENT ON COLUMN USERS.userId IS '20자, 영어소문자,숫자만 사용가능';
COMMENT ON COLUMN USERS.userPassword IS '영어대소문자특문 포함';
COMMENT ON COLUMN USERS.userProfile IS '기본값에 기본 프사 지정';



